# Generated by Django 5.2.6 on 2025-09-09 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Organisme')),
                ('issue_date', models.DateField(verbose_name="Date d'obtention")),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID de certification')),
                ('credential_url', models.URLField(blank=True, verbose_name='URL de vérification')),
                ('certificate_file', models.FileField(blank=True, upload_to='certificates/', verbose_name='Fichier certificat')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Répondu')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bachelor', 'Licence'), ('master', 'Master'), ('phd', 'Doctorat'), ('diploma', 'Diplôme'), ('certificate', 'Certificat')], max_length=20, verbose_name='Diplôme')),
                ('field_of_study', models.CharField(max_length=200, verbose_name="Domaine d'étude")),
                ('institution', models.CharField(max_length=200, verbose_name='Institution')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='En cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Note/Mention')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Poste')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('job_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contrat'), ('internship', 'Stage'), ('freelance', 'Freelance')], max_length=20, verbose_name="Type d'emploi")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('description', models.TextField(verbose_name='Description')),
                ('achievements', models.TextField(blank=True, verbose_name='Réalisations')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='Technologies utilisées')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('website', models.URLField(blank=True, verbose_name='Site Web')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/', verbose_name='Photo de profil')),
                ('cv_file', models.FileField(blank=True, upload_to='cv/', verbose_name='CV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('technologies', models.CharField(max_length=500, verbose_name='Technologies')),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('in_progress', 'En cours'), ('planned', 'Planifié')], default='completed', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('project_url', models.URLField(blank=True, verbose_name='URL du projet')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Projet vedette')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Portfolio', max_length=100, verbose_name='Titre du site')),
                ('site_description', models.TextField(blank=True, verbose_name='Description du site')),
                ('footer_text', models.CharField(blank=True, max_length=200, verbose_name='Texte du footer')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('category', models.CharField(choices=[('technical', 'Technique'), ('soft', 'Soft Skills'), ('language', 'Langue'), ('tool', 'Outil')], max_length=20, verbose_name='Catégorie')),
                ('proficiency', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], max_length=20, verbose_name='Niveau')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Compétence principale')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category', 'name'],
            },
        ),
    ]
