# Generated by Django 4.2.16 on 2025-09-12 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_collaboration_faq_resource_searchquery_tag_timeline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboration',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Collaboration', 'verbose_name_plural': 'Collaborations'},
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='collaboration_type',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='is_ongoing',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='partner_logo',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='website',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='category',
            field=models.CharField(choices=[('web', 'Développement Web'), ('mobile', 'Application Mobile'), ('ai', 'Intelligence Artificielle'), ('data', 'Data Science'), ('design', 'Design UI/UX'), ('consulting', 'Consulting'), ('other', 'Autre')], default='web', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='challenges_faced',
            field=models.TextField(blank=True, verbose_name='Défis rencontrés'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='client',
            field=models.CharField(blank=True, max_length=200, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboration',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='URL de démo'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='URL GitHub'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collaborations/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='project_url',
            field=models.URLField(blank=True, verbose_name='URL du projet'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='results_achieved',
            field=models.TextField(blank=True, verbose_name='Résultats obtenus'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboration',
            name='status',
            field=models.CharField(choices=[('completed', 'Terminé'), ('ongoing', 'En cours'), ('planned', 'Planifié')], default='completed', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Taille de l'équipe"),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='technologies',
            field=models.CharField(default=django.utils.timezone.now, help_text='Séparées par des virgules', max_length=500, verbose_name='Technologies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboration',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Titre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
